name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - main # 监听 main 分支推送

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Build VitePress site
        run: pnpm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: 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
          publish_dir: ./docs/.vitepress/dist
